/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laptop
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    private static int xx, xy;

    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnJadwal = new javax.swing.JButton();
        btnJadwal1 = new javax.swing.JButton();
        btnJadwal2 = new javax.swing.JButton();
        btnJadwal3 = new javax.swing.JButton();
        btnJadwal4 = new javax.swing.JButton();
        btnJadwal5 = new javax.swing.JButton();
        btnJadwal6 = new javax.swing.JButton();
        btnJadwal7 = new javax.swing.JButton();
        btnRegister1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(175, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(70, 130, 180));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_Close_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_minimize_window_20px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 130, 180));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Booking");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 450, -1));

        btnJadwal.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal.setText("Selasa, 2023-06-13, 15.00"); // NOI18N
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 190, -1));

        btnJadwal1.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal1.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal1.setText("<html> <p>Senin - Jumat : 15.00 - 18.00 -> 40.000</p> <p>Minggu : 07.00 - 17.00 -> 50.000</p> </html>"); // NOI18N
        btnJadwal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 250, 40));

        btnJadwal2.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal2.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal2.setText("Minggu, 2023-06-18, 07.00 - 17.00"); // NOI18N
        btnJadwal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 250, -1));

        btnJadwal3.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal3.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal3.setText("Senin, 2023-06-12, 15.00"); // NOI18N
        btnJadwal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, -1));

        btnJadwal4.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal4.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal4.setText("Rabu, 2023-06-14, 15.00"); // NOI18N
        btnJadwal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, -1));

        btnJadwal5.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal5.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal5.setText("Kamis, 2023-06-15, 15.00"); // NOI18N
        btnJadwal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 190, -1));

        btnJadwal6.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal6.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal6.setText("Sabtu, 2023-06-17, 15.00"); // NOI18N
        btnJadwal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, -1));

        btnJadwal7.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal7.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal7.setText("Jum'at, 2023-06-16, 15.00"); // NOI18N
        btnJadwal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        btnRegister1.setBackground(new java.awt.Color(70, 130, 180));
        btnRegister1.setForeground(new java.awt.Color(255, 245, 238));
        btnRegister1.setText("Back");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(451, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnJadwal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal1ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal1ActionPerformed

    private void btnJadwal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal2ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal2ActionPerformed

    private void btnJadwal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal3ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal3ActionPerformed

    private void btnJadwal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal4ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal4ActionPerformed

    private void btnJadwal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal5ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal5ActionPerformed

    private void btnJadwal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal6ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal6ActionPerformed

    private void btnJadwal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal7ActionPerformed
        // TODO add your handling code here:
        new BookingTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal7ActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegister1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnJadwal1;
    private javax.swing.JButton btnJadwal2;
    private javax.swing.JButton btnJadwal3;
    private javax.swing.JButton btnJadwal4;
    private javax.swing.JButton btnJadwal5;
    private javax.swing.JButton btnJadwal6;
    private javax.swing.JButton btnJadwal7;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
