/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;

/**
 *
 * @author laptop
 */
public class Print extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private Connection connection;
    private int id_ticket;
    /**
     * Creates new form Print
     */
    
    private static int xx, xy;
    
    public Print() {
        initComponents();
        initTable();
        readData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnJadwal2 = new javax.swing.JButton();
        btnJadwal3 = new javax.swing.JButton();
        btnJadwal5 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(175, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(70, 130, 180));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_Close_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_minimize_window_20px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 130, 180));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Data Ticket");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 50, 550, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Tanggal", "Jumlah Tiket", "Harga", "Total Harga"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 90));

        btnJadwal2.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal2.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal2.setText("Print"); // NOI18N
        btnJadwal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        btnJadwal3.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal3.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal3.setText("Exit"); // NOI18N
        btnJadwal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, -1));

        btnJadwal5.setBackground(new java.awt.Color(70, 130, 180));
        btnJadwal5.setForeground(new java.awt.Color(255, 245, 238));
        btnJadwal5.setText("Menu"); // NOI18N
        btnJadwal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwal5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 60, -1));

        btnHapus.setBackground(new java.awt.Color(70, 130, 180));
        btnHapus.setForeground(new java.awt.Color(255, 245, 238));
        btnHapus.setText("Hapus"); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 70, -1));

        btnEdit.setBackground(new java.awt.Color(70, 130, 180));
        btnEdit.setForeground(new java.awt.Color(255, 245, 238));
        btnEdit.setText("Edit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(560, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void btnJadwal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Ticket Waterpark");
        MessageFormat footer = new MessageFormat("Page {0}");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnJadwal2ActionPerformed

    private void btnJadwal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnJadwal3ActionPerformed

    private void btnJadwal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwal5ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwal5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row= jTable1.getSelectedRow();
        if (row==-1) {
            return;
        }

        this.id_ticket = Integer.parseInt((String) tableModel.getValueAt(row, 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        connection = Koneksi.getKoneksi();
        String query = "DELETE FROM ticket WHERE id=?";

        try {
            PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
            statement.setInt(1, this.id_ticket);
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat delete data, silahkan coba lagi!");
        } finally {
            readData();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int rowCount = tableModel.getRowCount();

        String query = "UPDATE ticket SET nama = ?, tanggal = ?, jumlah_tiket=?, harga=?, total_harga=? WHERE id = ?"; // Replace with your table and column names

        for (int row = 0; row < rowCount; row++) {
            try{
                PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);

                int id = Integer.parseInt((String) tableModel.getValueAt(row, 0));
                String nama = (String) tableModel.getValueAt(row, 1);
                String tanggal = (String) tableModel.getValueAt(row, 2);
                int jumlah_tiket = Integer.parseInt((String) tableModel.getValueAt(row, 3));
                double harga = Double.parseDouble((String) tableModel.getValueAt(row, 4));
                double total_harga = Double.parseDouble((String) tableModel.getValueAt(row, 5));

                statement.setString(1, nama);
                statement.setString(2, tanggal);
                statement.setInt(3, jumlah_tiket);
                statement.setDouble(4, harga);
                statement.setDouble(5, total_harga);
                statement.setInt(6, id);

                statement.executeUpdate();
            }catch (SQLException e){
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnJadwal2;
    private javax.swing.JButton btnJadwal3;
    private javax.swing.JButton btnJadwal5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initTable(){
        tableModel = new DefaultTableModel();
        jTable1.setModel(tableModel);
        tableModel.addColumn("Id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Tanggal");
        tableModel.addColumn("Jumlah Tiket");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Total Harga");
    }

    private void readData(){
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        try{
            connection = Koneksi.getKoneksi();
            String query = "SELECT * FROM ticket";

            Statement statement = (Statement) connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);

            //mengisi tabel dgn data hasil query
            while (resultSet.next()){
                Object[] ticket = new Object[6];
                ticket[0] = resultSet.getString("id");
                ticket[1] = resultSet.getString("nama");
                ticket[2] = resultSet.getString("tanggal");
                ticket[3] = resultSet.getString("jumlah_tiket");
                ticket[4] = resultSet.getString("harga");
                ticket[5] = resultSet.getString("total_harga");

                tableModel.addRow(ticket);
            }
            resultSet.close();
            statement.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
}
